channels:
- conda-forge
dependencies:
- python>=3.8
- ipywidgets>=7.6.5
- notebook
- jupyter
- rasterio
- rioxarray
- xarray
- geopandas
- shapely
- ipython
- pyyaml
- netCDF4
- pandas
- numpy
- matplotlib
- numba
- schema
- termcolor
- papermill>=2.3.4
- alive-progress>=3.0.1
- fiona>=1.8.21
- owslib==0.27.2
- requests==2.28.1
- pytest
- eeharvest
  
