channels:
- conda-forge
dependencies:
- python>=3.9
- ipywidgets>=7.6.5
- notebook
- jupyter
- pip
- rasterio
- rioxarray
- xarray
- geopandas
- shapely
- ipython
- pyyaml
- netCDF4
- pandas
- numpy
- matplotlib
- numba
- schema
- termcolor
- pip:
  - alive-progress>=3.0.1
  - eeharvest
  - fiona>=1.8.21
  - owslib==0.27.2
  - papermill>=2.3.4
  - pytest>=7.1.2
  - pytest-cov>=3.0.0
  - requests==2.28.1
