project:
  type: website
editor:
  render-on-save: true
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Geodata-Harvester"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - py_dataharvester.qmd
      - R_dataharvester.qmd
      - contributing.qmd
      - events.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



